// AUTO-GENERATED by .ds-sync/collect-heavy-imports.mjs — do not hand-edit names.
// ESM universal stub for heavy libs (assistant-ui / @tiptap / streamdown / ai / zod).
// MUST be ESM: esbuild static-binds ESM named imports, but runs CJS through
// __toESM (copies only own enumerable props — none on a proxy) so a CJS proxy
// would bind every named import to undefined and crash IIFE eval. P is a
// self-returning proxy: every get/call/construct yields P, so module-top-level
// use (z.object({...}), StarterKit.configure()) never throws at load. Components
// that truly render these libs fail at RENDER → auto floor card (intended).
const P = new Proxy(function stub() {}, {
  get(_t, k) {
    if (k === '__esModule') return true;
    if (k === 'then') return undefined;
    if (k === Symbol.toPrimitive) return () => '';
    if (k === Symbol.toStringTag) return 'Module';
    if (k === Symbol.iterator) return function* () {};
    return P;
  },
  apply: () => P,
  construct: () => P,
});
export default P;
export {
  P as ActionBarPrimitive,
  P as AppendMessage,
  P as AssistantChatTransport,
  P as AssistantRuntime,
  P as AssistantRuntimeProvider,
  P as AssistantState,
  P as AuiIf,
  P as BackgroundColor,
  P as Color,
  P as ComposerPrimitive,
  P as Editor,
  P as EditorContent,
  P as FontFamily,
  P as FontSize,
  P as LexicalComposerInput,
  P as MessagePrimitive,
  P as MessageStatus,
  P as MessageTiming,
  P as ReasoningMessagePartProps,
  P as SourceMessagePartComponent,
  P as Streamdown,
  P as StreamdownTranslations,
  P as TextMessagePartProps,
  P as TextStyle,
  P as ThreadMessageLike,
  P as ThreadPrimitive,
  P as ToolCallMessagePartComponent,
  P as ToolCallMessagePartProps,
  P as UIMessage,
  P as Unstable_DirectiveFormatter,
  P as Unstable_IconComponent,
  P as Unstable_SlashCommand,
  P as Unstable_TriggerItem,
  P as unstable_defaultDirectiveFormatter,
  P as unstable_useSlashCommandAdapter,
  P as unstable_useTriggerPopoverScopeContext,
  P as useAui,
  P as useAuiState,
  P as useChatRuntime,
  P as useEditor,
  P as useEditorState,
  P as useExternalStoreRuntime,
  P as useMessage,
  P as useMessageTiming,
  P as z,
};
