// V2.1 阶段 3 — chat 数据模型类型（从 electron/main/chat_db.ts 下沉）。
//
// B-pure-unified：chat harness 逻辑搬到 shared/ 后在 UI 进程（renderer /
// browser）跑，需要这些数据模型类型但**不能**引 better-sqlite3（chat_db.ts
// 运行时留在 main）。把纯类型定义抽到这里（零运行时依赖，可被 shared/web 引），
// chat_db.ts re-export 保所有既有 importer（dispatcher/harness/kos_save/
// handlers 等）import 路径不变。
//
// 不变式 1：本文件**零 Electron/Node-only 依赖**（纯类型 + 派生自类型的纯逻辑，无 import）。
//
// 这些类型 1:1 对齐 ai_chat.db 的 ai_chat_sessions / ai_chat_messages /
// chat_tool_call 三表（CREATE 语句见 chat_db.ts），是 chat 持久化的契约面。
//
// 🔴 ChatSession / ChatMessage / ChatToolCall 在 `shared/api/types/chat.ts` 还有**第二份
// 手抄**（API/IPC 边界投影，renderer 按那份取字段）。加列时两处必须同批改 —— 只改这里
// 不会有任何报错（两条读路径都 SELECT *，列照传），但边界类型会开始对 wire 形状撒谎。
// 实测踩过两次：ui_message_json(v9)、whitelist_rule_id(v18)。
// 对账闸 = tests/config/test_chat_type_mirror_parity.py。

// 'ai-sdk' (P4 Phase 06a cutover) is a persistable session kind: a chat authored through the embedded
// AI SDK Gateway. The legacy engine never DISPATCHES it (mapStart/mapEdit guard via
// assertLegacyBackendKind + the backends Partial record has no ai-sdk entry → getBackend throws), but
// createNewSession must be able to INSERT the row — onEnsureSession creates it before the gateway run.
export type BackendKind = 'notion-agent' | 'custom-api' | 'ai-sdk'
export type MessageRole = 'user' | 'assistant' | 'system' | 'tool'
export type MessageStatus = 'pending' | 'streaming' | 'complete' | 'error' | 'aborted'

// task 06-18-custom-ai-harness-agent Phase 2 (P2c) — chat session anchor.
//   'email'   = anchored to a specific inbox email (email_id NOT NULL, anchor_id = email_id).
//   'general' = a context-free agent session (Cmd+O in P3); email_id IS NULL, anchor_id IS NULL.
//   'matter'  = anchored to a Matter internal integer id; email_id IS NULL, anchor_id = matter id.
// The ai_chat_sessions v7 migration adds a table CHECK coupling anchor_type ↔ email_id/anchor_id
// so a sentinel like email_id=0 is impossible by construction (architecture.md §1.4 / DR-5).
export type AnchorType = 'email' | 'general' | 'matter'
// FILTER vocabulary (≠ the origin column's free-text value domain, which gained 'im' in CHAT_DB
// v22): stage 2 PR-1 adds no IM filter — im rows ride the default 'interactive' clause (Q18=A).
// Mirror: api/types/chat.ts (parity gate) + the two Python mirrors, see that file's red note.
export type ChatSessionOriginFilter = 'interactive' | 'agent' | 'im' | 'all'
export type ChatSessionTriggerKind =
  | 'manual'
  | 'cron'
  | 'schedule'
  | 'email_filter'
  | 'calendar_event_change'
  | 'calendar_before_start'

// Sprint 19 — agent harness audit. Each LLM-proposed tool call gets one row
// in `chat_tool_call`. See docs/reference/llm-agent/agent-harness-design.md §4.5.
export type ToolCallStatus =
  | 'pending' // awaiting confirmation (tier=preview/edit)
  | 'confirmed' // user approved, not yet running
  | 'running' // handler in flight
  | 'ok' // handler returned success
  | 'error' // handler returned ToolResult.ok=false OR threw
  | 'canceled' // user clicked Cancel in ConfirmToolDialog
export type ConfirmationTier = 'silent' | 'preview' | 'edit'

export interface ChatSession {
  id: number
  // P2c — nullable since v7: email sessions carry the internal_id, general
  // sessions carry null. Read sites that only ever handle the per-email sidebar
  // (anchor_type='email') still see a number; cross-anchor consumers must null-check.
  email_id: number | null
  // P2c — anchor model (v7). Pre-v7 rows backfill to anchor_type='email',
  // anchor_id=email_id. 'general' rows have both email_id and anchor_id NULL.
  anchor_type: AnchorType
  anchor_id: number | null
  backend_kind: BackendKind
  backend_model: string | null
  backend_agent_page_id: string | null
  // Phase 10 (demo-fidelity) — optional session title (auto-generated by a haiku call after the first
  // turn, user-renamable). null when unset; the UI then derives a title from the email subject / first
  // user message. ai_chat.db v14 additive column.
  title: string | null
  // dogfood-2 — soft-delete: archived=true hides the session from listAllSessions without deleting the
  // row. ai_chat.db v15 additive column (DEFAULT 0, existing rows read as false).
  archived: boolean
  created_at: number
  updated_at: number
  // S4 W3 (task 07-02-s4-custom-agent-core) — headless custom-agent run provenance. 'agent' for a
  // cron/email-triggered headless session; null/undefined for every interactive session. agent_id +
  // agent_job_id (the async_jobs.job_id as TEXT) link back to report_agent + async_jobs. All three are
  // ai_chat.db v19 additive columns; optional here so pre-v19 rows + interactive-session literals stay
  // valid.
  origin?: string | null
  agent_id?: string | null
  agent_job_id?: string | null
  trigger_id?: string | null
  trigger_kind?: ChatSessionTriggerKind | string | null
  trigger_fired_at?: number | null
  // harness-chat lane A B4 (task 07-15) — per-session read watermark (ai_chat.db v20 additive
  // column). NULL/undefined = never marked read (no badge); unread = updated_at > last_read_at.
  last_read_at?: number | null
  // custom-agent epic W3 (ai_chat.db v21) — a nullable pin-order timestamp plus an independent star
  // marker. SQLite crosses the untyped boundary as 0/1, hence the tolerant starred wire shape.
  pinned_at?: number | null
  starred?: boolean | number
}

// Global session-history row. Unlike `ChatSession` (per-email, used by the
// in-panel sidebar), this carries enough to render a cross-email history list
// without an N+1 listMessages round-trip per row: the first user-message
// preview and the message count are aggregated in the same SELECT. The
// owning email's subject/sender are NOT here — they live in sync_store.db, so
// handlers/chat.ts joins them in best-effort after the fact.
export interface ChatSessionSummary extends ChatSession {
  /** First user-authored message, truncated server-side. Null for sessions
   *  seeded by automation that never got a user turn. */
  first_user_message: string | null
  message_count: number
}

export interface ChatMessage {
  id: number
  session_id: number
  role: MessageRole
  content: string
  tokens_input: number | null
  tokens_output: number | null
  cost_usd: number | null
  model: string | null
  status: MessageStatus
  error_message: string | null
  // schema_version=2 (Sprint 4 review opus L carry-forward): JSON blob
  // for backend-specific data that doesn't fit the shared columns. Used
  // today by notion_agent to persist thread_id without abusing the
  // `model` column. Null when no extras. NEVER store secrets here —
  // the field crosses the IPC boundary.
  metadata: string | null
  // task 06-08-chat 需求 5 — extended-thinking summary (Claude extended thinking).
  // First-class column (not metadata) because it's body-level content: streamed,
  // rendered in a collapsible block above the answer, and reloaded from the DB.
  // Null for non-thinking turns + all pre-v6 rows (ALTER ADD default). chat_db.ts
  // v6 migration adds the column; serve-api db.py mirrors the read/write.
  thinking: string | null
  // v9 (P4 Phase 02 — chat-panel AI SDK Gateway) — the AI SDK v6 UIMessage
  // canonical JSON for this turn. The gateway runtime dual-writes it next to
  // `content` (extracted text); legacy-runtime rows + all pre-v9 rows stay NULL
  // and the reload converter synthesizes a UIMessage from `content`. chat_db.ts
  // v9 migration adds the column; serve-api db.py mirrors read (SELECT *) + write.
  // NEVER store secrets here — the field crosses the IPC boundary.
  ui_message_json: string | null
  // v23 (WP-15 context 环, task 08-05) — 本回合最后一次 provider 调用的 prompt token 数 =
  // 「上下文占用」。🔴 与 tokens_input 语义不同：那一列是 ai@7 的多 step **求和**，工具循环回合
  // 里会把同一段 prompt 计好几遍；这一列是**末 step** 的 inputTokens（chatRun.ts
  // lastStepContextTokens）。null = legacy / pre-v23 行 / 非 gateway 写入 → 前端不渲染 context 环。
  context_tokens: number | null
  created_at: number
  updated_at: number
}

// AgentMemoryEntry + WriteMemoryInput 已于 v16 (M5b, 2026-06-30) 随 agent_memory_kv 表退役。
// 记忆终态 = user.md(M3) + mem0(M1/M2)。

export interface OpenSessionInput {
  // P2c — anchor-aware session open. Back-compat: existing callers pass
  // `{ emailId }` (anchorType defaults to 'email'); general sessions pass
  // `{ anchorType: 'general' }` and omit emailId. NEVER pass emailId=0 as a
  // general sentinel — the v7 CHECK rejects it.
  anchorType?: AnchorType
  /** Required when anchorType is 'email' (the default); ignored for 'general'. */
  emailId?: number | null
  /** Required positive internal Matter id when anchorType is 'matter'. */
  matterId?: number
  backendKind: BackendKind
  backendModel?: string | null
  backendAgentPageId?: string | null
  title?: string | null
}

export interface AppendMessageInput {
  sessionId: number
  role: MessageRole
  content: string
  status: MessageStatus
  model?: string | null
  tokensInput?: number | null
  tokensOutput?: number | null
  costUsd?: number | null
  errorMessage?: string | null
  metadata?: string | null
  // v9 (P4 Phase 02) — AI SDK UIMessage canonical JSON. Gateway runtime sets it;
  // legacy callers omit → persisted NULL (reload synthesizes from content).
  uiMessageJson?: string | null
  // v23 (WP-15 context 环) — 末 step 的 inputTokens（≠ tokensInput 的多 step 求和）。
  // 只有 gateway persistTurn 写；其余调用方省略 → NULL。
  contextTokens?: number | null
}

export interface UpdateMessagePatch {
  content?: string
  status?: MessageStatus
  tokensInput?: number | null
  tokensOutput?: number | null
  costUsd?: number | null
  errorMessage?: string | null
  model?: string | null
  metadata?: string | null
  // task 06-08-chat 需求 5 — finalizeMessage persists the full thinking buffer
  // here (harness streams it live, writes it on终态). Omitted on non-thinking turns.
  thinking?: string | null
  // v9 (P4 Phase 02) — AI SDK UIMessage canonical JSON, finalized on turn end.
  uiMessageJson?: string | null
  // v23 (WP-15 context 环) — 审批暂停的行在 resume 落库时才拿到 context 占用（暂停那一段
  // 早退不落库），故 update 面也要能写这一列。
  contextTokens?: number | null
}

// Sprint 19 — chat_tool_call row + CRUD inputs.

export interface ChatToolCall {
  id: number
  message_id: number
  /** Anthropic toolu_xxx. MUST match across `tool_use` → `tool_result`
   *  round-trip in the LLM message stream. UNIQUE per (message_id). */
  tool_use_id: string
  tool_name: string
  /** Original LLM-proposed input, serialized JSON. */
  input_json: string
  /** Set only when tier was 'edit' and the user changed the input via the
   *  ConfirmToolDialog. The tool handler receives this as effective input;
   *  the result envelope returned to the LLM includes
   *  `{ user_edited: true, original_input, final_input }` so the model
   *  knows what was actually executed. */
  user_edited_input_json: string | null
  /** Tool handler's `ToolResult` serialized as JSON. Null until completion. */
  output_json: string | null
  status: ToolCallStatus
  duration_ms: number | null
  confirmation_tier: ConfirmationTier
  /** Epoch ms when the user clicked Confirm. Null for silent / canceled. */
  confirmed_at: number | null
  /** task 06-08-chat Bug 2 — character offset into the parent assistant
   *  message's `content` at which this tool call was proposed (= the running
   *  buffer length when the harness saw the `tool_use` block, i.e. after this
   *  iter's text but before the next iter's). The renderer splits `content` at
   *  these offsets to interleave tool chips in time order ("text → tool → more
   *  text") instead of stacking all chips below the body. Null for rows written
   *  before v5 (and for non-custom-api / non-harness paths) → renderer falls
   *  back to the legacy "all chips after the body" layout. */
  content_offset: number | null
  /** Phase 03b (v10) — write-tool approval outcome: 'approved' / 'edited' / 'rejected'
   *  for AI SDK Gateway HITL write tools; NULL for read tools + legacy harness rows.
   *  Optional: absent on rows read from a pre-v10 DB / older serve-api JSON. */
  approval_status?: string | null
  /** Phase 03b (v10) — sha256 of the approved input (the domain ApprovalGuard binding).
   *  NULL for read tools + legacy rows. Optional (see approval_status). */
  approval_hash?: string | null
  /** Phase 04a (v11) — the A2UI render payload (component + props + audit, protocol §3) the
   *  rich tool card showed for an AI SDK Gateway write tool. NULL for read tools / legacy rows
   *  / flag-off writes. Optional (absent on rows from a pre-v11 DB / older serve-api JSON). */
  ui_payload_json?: string | null
  /** Phase 04b (v12) — outbound-send (email_prepare_send) only: sha256 of the canonical outbound
   *  payload that bound the approved content to what was sent. NULL for every other tool / legacy
   *  row. Optional (absent on rows from a pre-v12 DB / older serve-api JSON). */
  content_hash?: string | null
  /** Phase 04b (v12) — outbound-send only: the one-shot idempotency key the Python send ledger
   *  keyed on (a replay never re-sends). NULL otherwise. Optional (see content_hash). */
  idempotency_key?: string | null
  /** S2 W1 (v18) — exec tools only: the PolicyRule id that auto-allowed the run without a card
   *  (approval_status='auto_whitelist'). NULL for card-approved / read / legacy rows. Optional
   *  (absent on rows from a pre-v18 DB / older serve-api JSON). */
  whitelist_rule_id?: number | null
  created_at: number
  updated_at: number
}

export interface AppendToolCallInput {
  messageId: number
  toolUseId: string
  toolName: string
  inputJson: string
  confirmationTier: ConfirmationTier
  /** Initial status — usually 'pending' for preview/edit tiers, 'running'
   *  for silent. */
  status: ToolCallStatus
  /** task 06-08-chat Bug 2 — running content length at the moment the harness
   *  saw the tool_use block (insertion point for time-ordered interleaving).
   *  Omitted by callers that don't track it → persisted as NULL. */
  contentOffset?: number
}

export interface UpdateToolCallPatch {
  status?: ToolCallStatus
  outputJson?: string | null
  durationMs?: number | null
  userEditedInputJson?: string | null
  confirmedAt?: number | null
  /** Phase 03b (v10) — write-tool approval outcome ('approved'/'edited'/'rejected'). */
  approvalStatus?: string | null
  /** Phase 03b (v10) — sha256 of the approved input (domain ApprovalGuard binding). */
  approvalHash?: string | null
  /** Phase 04a (v11) — the A2UI render payload (JSON) the rich tool card showed. */
  uiPayloadJson?: string | null
  /** Phase 04b (v12) — outbound-send content hash (sha256 of the canonical outbound payload). */
  contentHash?: string | null
  /** Phase 04b (v12) — outbound-send one-shot idempotency key (the send ledger key). */
  idempotencyKey?: string | null
  /** S2 W1 (v18) — exec whitelist rule id (approval_status='auto_whitelist'). */
  whitelistRuleId?: number | null
}

// ── 后端能力查询（派生自 BackendKind 的纯逻辑）──────────────────────────────
// V2.1 阶段 3：从 chat/config.ts 下沉。dispatcher 下沉 shared 后需在 UI 进程做
// harness-vs-legacy gate，但 config.ts（env 读）留 main —— 而这函数是 backend 的
// 静态能力声明（与 env 无关），故跟 BackendKind 一起落 shared，单一真源在此。

/** 某 backend kind 是否端到端支持 Anthropic tool_use 协议（驱动 dispatcher 的
 *  harness vs legacy 单遍 gate）。notion-agent CLI 是黑盒一次性调用，无 tool_use
 *  循环。纯静态映射 —— 未来加 backend 在此扩展。 */
export function backendSupportsTools(kind: BackendKind): boolean {
  return kind === 'custom-api'
}
