// REVIEW-LOG C-03 codegen pipeline. Walks ../docs/cli-schema/*.schema.json
// and emits a single shared/types/cli.gen.ts file the renderer + main process
// + future Web SPA all import. Sprint 1 will replace `unknown` placeholders
// in shared/api/types.ts with the codegen output types.

import { readdirSync, readFileSync, mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { compile } from 'json-schema-to-typescript'

const HERE = dirname(fileURLToPath(import.meta.url))
const SCHEMA_DIR = resolve(HERE, '../../docs/cli-schema')
const OUT_FILE = resolve(HERE, '../src/shared/types/cli.gen.ts')

function toTypeName(slug: string): string {
  // "email-list" → "EmailList"
  return slug
    .split(/[-_.]/)
    .filter(Boolean)
    .map((p) => p[0].toUpperCase() + p.slice(1))
    .join('')
}

async function main(): Promise<void> {
  const files = readdirSync(SCHEMA_DIR)
    .filter((f) => f.endsWith('.schema.json'))
    .filter((f) => f !== '_common.schema.json')
    .sort()

  const banner =
    `// AUTO-GENERATED by scripts/gen-types.ts — do not edit by hand.\n` +
    `// Source: docs/cli-schema/*.schema.json. Regenerate with \`pnpm gen:types\`.\n\n`

  const blocks: string[] = []
  for (const f of files) {
    const slug = f.replace(/\.schema\.json$/, '')
    const typeName = toTypeName(slug)
    const schemaPath = join(SCHEMA_DIR, f)
    const schema = JSON.parse(readFileSync(schemaPath, 'utf8'))
    const ts = await compile(schema, typeName, {
      bannerComment: '',
      additionalProperties: false,
      cwd: SCHEMA_DIR, // resolve $ref to ./_common.schema.json relative to schema dir
      style: { singleQuote: true, semi: false }
    })
    blocks.push(`// from ${f}\n${ts}`)
  }

  mkdirSync(dirname(OUT_FILE), { recursive: true })
  writeFileSync(OUT_FILE, banner + blocks.join('\n'), 'utf8')
  console.log(`gen:types → ${OUT_FILE} (${files.length} schemas)`)
}

main().catch((err) => {
  console.error('gen:types failed:', err)
  process.exit(1)
})
