// REVIEW-LOG C-03 codegen pipeline. Walks ../docs/cli-schema/*.schema.json
// and emits a single shared/types/cli.gen.ts file the renderer + main process
// + future Web SPA all import. Sprint 1 will replace `unknown` placeholders
// in shared/api/types.ts with the codegen output types.

import { readdirSync, readFileSync, mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { compile } from 'json-schema-to-typescript'

const HERE = dirname(fileURLToPath(import.meta.url))
const SCHEMA_DIR = resolve(HERE, '../../docs/cli-schema')
const OUT_FILE = resolve(HERE, '../src/shared/types/cli.gen.ts')

function toTypeName(slug: string): string {
  // "email-list" → "EmailList"
  return slug
    .split(/[-_.]/)
    .filter(Boolean)
    .map((p) => p[0].toUpperCase() + p.slice(1))
    .join('')
}

/**
 * Each schema emits multiple anonymous sub-interfaces (Data / Summary /
 * ResultWrapper / WrapperError / Meta / Error). Concatenating 45 schemas
 * into one .ts file collides those names — and TS declaration-merge fails
 * when two interfaces named `Data` have different `action` literals.
 *
 * Fix: every non-root identifier in a schema block is prefixed with that
 * block's root type name. `Meta` in email-list block becomes
 * `MailagentEmailList_Meta`; `Meta` in email-body becomes
 * `MailagentEmailBody_Meta`; etc. Cross-block names that are intentionally
 * stable (`EmailListItem`, `EmailRecord`, `SearchHit`, `AttachmentItem`)
 * are still defined inside their owning schema block, so callers reach for
 * them via the prefixed form too (e.g. `MailagentEmailList_EmailListItem`).
 *
 * Trade-off: identifiers grow longer, but every consumer reads from the
 * generated file via import statements, not hand-typing — and the cost
 * is one extra word vs. an entire ts-morph rewrite pipeline.
 */
function rewriteSubTypes(src: string, prefix: string): { src: string; rootName: string } {
  // The root type name comes from the schema's `title` (not the slug-derived
  // hint we pass to compile()), so we recover it from the first `export type`
  // or `export interface` in the generated source. Everything *else* gets the
  // slug-derived prefix to keep names unique across the concatenated file.
  const firstExport = src.match(/^export (?:interface|type) (\w+)/m)
  if (!firstExport) {
    throw new Error('rewriteSubTypes: no export found in compiled output')
  }
  const rootName = firstExport[1]
  const declared = new Set<string>()
  for (const m of src.matchAll(/^export (?:interface|type) (\w+)/gm)) {
    const name = m[1]
    if (name !== rootName) declared.add(name)
  }
  // Sort by length desc so substring collisions resolve correctly
  // (e.g. rename `ResultWrapper` before `Result`).
  const ordered = [...declared].sort((a, b) => b.length - a.length)
  let out = src
  for (const name of ordered) {
    const re = new RegExp(`\\b${name}\\b`, 'g')
    out = out.replace(re, `${prefix}_${name}`)
  }
  return { src: out, rootName }
}

async function main(): Promise<void> {
  const files = readdirSync(SCHEMA_DIR)
    .filter((f) => f.endsWith('.schema.json'))
    .filter((f) => f !== '_common.schema.json')
    .sort()

  const banner =
    `// AUTO-GENERATED by scripts/gen-types.ts — do not edit by hand.\n` +
    `// Source: docs/cli-schema/*.schema.json. Regenerate with \`pnpm gen:types\`.\n` +
    `// Sub-interfaces are prefixed with their root type name to avoid cross-\n` +
    `// schema name collisions (e.g. \`MailagentEmailList_Meta\`).\n\n`

  const blocks: string[] = []
  for (const f of files) {
    const slug = f.replace(/\.schema\.json$/, '')
    const typeName = toTypeName(slug)
    const schemaPath = join(SCHEMA_DIR, f)
    const schema = JSON.parse(readFileSync(schemaPath, 'utf8'))
    const raw = await compile(schema, typeName, {
      bannerComment: '',
      additionalProperties: false,
      cwd: SCHEMA_DIR, // resolve $ref to ./_common.schema.json relative to schema dir
      style: { singleQuote: true, semi: false }
    })
    const { src: prefixed, rootName } = rewriteSubTypes(raw, typeName)
    blocks.push(`// from ${f} — root: ${rootName}\n${prefixed}`)
  }

  mkdirSync(dirname(OUT_FILE), { recursive: true })
  writeFileSync(OUT_FILE, banner + blocks.join('\n'), 'utf8')
  console.log(`gen:types → ${OUT_FILE} (${files.length} schemas)`)
}

main().catch((err) => {
  console.error('gen:types failed:', err)
  process.exit(1)
})
