// 工具中文显示名 —— gateway 注入用的**零依赖叶子模块**。
//
// gateway（frontend/src/ai-gateway/**）是纯 TS，不依赖 renderer 的 i18n runtime，也不该为了一张
// 名字表把整份 locale JSON 拖进 Electron main 的包里。所以这里放一份只含工具名→中文名的常量表，
// 由 buildGatewayTools() 在装配末尾拼进 description（`「检索事项」Find Matters by …`），让模型能
// 把用户说的「事项」这类中文概念接到对应工具族上。
//
// 🔴 这是 renderer i18n `chat.toolTitle.*`（zh-CN）的镜像，键集与值必须逐条相同 ——
//    闸在 frontend/tests/shared/toolDisplayNames.test.ts（抽取失败必红）。改名字只有一个动作：
//    两个 locale 的 chat.toolTitle + 这张表一起改。
//    renderer 侧继续读 i18n（tool_steps.ts 的 toolTitleKey），不从这里取。

/** 工具名 → 中文显示名。缺名的工具 description 原样不动（注入端跳过）。 */
export const TOOL_DISPLAY_NAMES_ZH: Readonly<Record<string, string>> = {
  email_list_filter: '筛选邮件',
  email_get: '读取邮件',
  email_body: '读取邮件正文',
  email_list_thread: '读取邮件会话',
  email_search_fulltext: '全文搜索邮件',
  email_search: '搜索邮件',
  email_search_attachments: '搜索附件',
  email_thread_attachments: '列出会话附件',
  email_attachment_text: '读取附件内容',
  email_flag: '标记旗标',
  email_archive: '归档邮件',
  email_pin: '置顶邮件',
  email_resync: '重新同步邮件',
  email_draft_reply: '起草回复',
  email_draft_compose: '起草新邮件',
  email_draft_update: '修改草稿',
  email_prepare_send: '准备发送邮件',
  report_list: '列出报告',
  report_get: '读取报告',
  report_write: '生成报告',
  kos_query: '查询知识图谱',
  kos_search: '搜索知识库',
  kos_get_page: '读取知识页',
  kos_find_experts: '查找相关同事',
  kos_list_pages: '列出知识页',
  kos_get_backlinks: '读取反向链接',
  agent_profile_read: '读取身份文档',
  agent_profile_history: '查看文档修改历史',
  agent_profile_restore: '回滚身份文档',
  agent_memory_update: '更新长期记忆',
  update_system_md: '修改身份文档',
  skill_read: '读取技能',
  discover_skills: '查找可用技能',
  set_skill_enabled: '开关技能',
  skill_install: '安装技能',
  skill_install_confirm: '确认安装技能',
  skill_uninstall: '卸载技能',
  skill_draft_create: '创建技能草稿',
  skill_draft_write_file: '写入技能草稿文件',
  skill_draft_read: '读取技能草稿',
  skill_draft_validate: '校验技能草稿',
  skill_draft_publish: '发布技能草稿',
  skill_draft_discard: '丢弃技能草稿',
  skill_list_installed: '列出已装技能',
  chat_session_list: '列出历史会话',
  agent_catalog_list: '列出 Agent 目录',
  agent_catalog_get: '读取 Agent 目录项',
  chat_session_search: '搜索历史会话',
  chat_session_get: '读取历史会话',
  custom_agent_list: '列出 Custom Agent',
  custom_agent_get: '读取 Custom Agent',
  custom_agent_create: '创建 Custom Agent',
  custom_agent_update: '修改 Custom Agent',
  custom_agent_delete: '删除 Custom Agent',
  custom_agent_run_now: '立即运行 Custom Agent',
  custom_agent_call: '调用 Custom Agent',
  group_history: '查看群聊记录',
  group_members: '查看群成员',
  group_post: '在群里发言',
  group_create: '创建群聊',
  internal_agent_list: '列出内建 Agent',
  internal_agent_get: '读取内建 Agent',
  internal_agent_update: '修改内建 Agent',
  matter_followup_mutate: '修改事项跟进配置',
  web_fetch: '抓取网页',
  web_search: '联网搜索',
  run_command: '执行命令',
  file_read: '读取文件',
  file_write: '写入文件',
  calendar_events_list: '查看日程',
  calendar_event_get: '读取日程',
  calendar_event_reschedule: '改期日程',
  calendar_event_rsvp: '回复会议邀请',
  calendar_event_delete: '删除日程',
  matter_find: '检索事项',
  matter_get: '读取事项',
  matter_create: '创建事项',
  matter_update: '更新事项',
  matter_item_mutate: '编辑事项条目',
  matter_progress_mutate: '记录事项进展',
  matter_item_report: '提交行动项执行结果',
  matter_resource_mutate: '关联事项资料',
  matter_stakeholder_mutate: '编辑事项干系人',
  matter_relation_mutate: '编辑事项关联',
  matter_add_note: '添加事项备注',
  matter_run_control: '控制跟进运行',
  matter_review_update: '评审更新提案',
  matter_update_propose: '提交更新提案',
  matter_attention_list: '查看关注信号',
  matter_attention_triage: '处置关注信号',
  matter_runs_list: '查看跟进记录',
  matter_tags_list: '查看事项标签',
  matter_suggestion_resolve: '处置资料建议',
  contact_search: '检索通讯录',
  contact_get: '查看联系人',
  contact_list_mails: '查看往来邮件',
  contact_propose_update: '提交联系人修改建议',
  contact_propose_merge: '提交联系人合并建议',
  contact_propose_relation: '提交汇报关系建议',
  contact_set_kind: '修改联系人分类',
  contact_mark_former_email: '标记曾用邮箱',
  contact_refresh_profile: '重新生成联系人画像',
  contact_update_fields: '修改联系人资料',
  contact_set_manager: '设置联系人上级',
  library_list: '浏览资料库',
  library_read: '读取资料库文件',
  library_search: '搜索资料库',
  library_append: '追加到资料库文件',
  library_write: '写入资料库文件',
  library_move: '移动资料库文件',
  library_delete: '删除资料库文件',
  notion_agent_chat: '咨询 Notion Agent',
  plan_update: '更新计划',
  suggest_followups: '准备追问建议',
  submit_feedback: '提交产品反馈',
  generate_image: '生成图片'
}
