import { AlertTriangle, Check, Loader2, Sparkles, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import type { MatterRun, MatterUpdateSummary } from '@shared/api/types/matter'

export function RunOverlay({ run, update, onReview, onClose }: { run: MatterRun; update?: MatterUpdateSummary; onReview(updateId: number): void; onClose(): void }): React.ReactElement {
  const { t } = useTranslation(); const [elapsed, setElapsed] = useState(0)
  useEffect(() => { if (run.lifecycle_state !== 'running') return; const timer = window.setInterval(() => setElapsed(Date.now() - (run.started_at ?? Date.now())), 1000); return () => window.clearInterval(timer) }, [run.lifecycle_state, run.started_at])
  useEffect(() => {
    const terminal = !['queued', 'running'].includes(run.lifecycle_state)
    if (!terminal || (update && (run.lifecycle_state === 'ok' || run.lifecycle_state === 'warn'))) return
    const timer = window.setTimeout(onClose, 10_000)
    return () => window.clearTimeout(timer)
  }, [onClose, run.lifecycle_state, update])
  const active = run.lifecycle_state === 'queued' || run.lifecycle_state === 'running'
  return <aside className="fixed bottom-5 right-5 z-40 w-[340px] rounded-[var(--r-card)] border border-ai/35 bg-ink-1 shadow-md"><header className="flex items-center gap-2 border-b border-ink-border px-4 py-3"><span className="relative flex size-2"><span className={active ? 'absolute inline-flex size-full animate-ping rounded-full bg-ai opacity-70' : ''}/><span className="relative inline-flex size-2 rounded-full bg-ai"/></span><strong className="text-body">{active ? t('matters.runOverlay.runningTitle', { defaultValue: '跟进运行中' }) : t('matters.runOverlay.doneTitle', { defaultValue: '跟进运行' })}</strong><span className="ml-auto font-mono text-[10px] text-ink-fg-3">{t('matters.runOverlay.capability', { defaultValue: '手动触发 · 观察+建议' })}</span><button type="button" onClick={onClose}><X size={14}/></button></header><div className="p-4"><div className="flex items-start gap-3">{active ? <Loader2 className="animate-spin text-ai" size={18}/> : run.lifecycle_state === 'fail' ? <AlertTriangle className="text-fail" size={18}/> : <Check className="text-ok" size={18}/>}<div><p className="text-body font-medium">{run.lifecycle_state === 'queued' ? t('matters.runs.queued', { defaultValue: '排队中' }) : run.lifecycle_state === 'running' ? t('matters.runs.running', { defaultValue: '读取与比对变化中' }) : run.lifecycle_state === 'ok' ? t('matters.runOverlay.proposal', { count: update?.change_count ?? 0, defaultValue: `已产出提案 · ${update?.change_count ?? 0} 项变化` }) : run.lifecycle_state === 'warn' ? t('matters.runOverlay.warn', { defaultValue: '已产出提案 · 部分降级' }) : run.lifecycle_state === 'noop' ? t('matters.runs.noChanges', { defaultValue: '未检出变化' }) : run.lifecycle_state === 'canceled' ? t('matters.runs.canceled', { defaultValue: '已取消' }) : String(run.error?.message ?? t('matters.runOverlay.failed', { defaultValue: '运行失败' }))}</p>{run.lifecycle_state === 'running' ? <p className="mt-1 font-mono text-meta text-ink-fg-3">{Math.floor(elapsed / 1000)}s</p> : null}</div></div>{update && (run.lifecycle_state === 'ok' || run.lifecycle_state === 'warn') ? <button type="button" onClick={() => onReview(update.id)} className="mt-4 inline-flex w-full items-center justify-center gap-1.5 rounded-[var(--r-ctl)] bg-ai px-3 py-2 text-body font-medium text-white"><Sparkles size={13}/>{t('matters.runOverlay.review', { defaultValue: '审阅' })}</button> : null}</div></aside>
}
